# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import dengjen_grpc_pb2 as dengjen__grpc__pb2


class DengjenGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDengjenVersion = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/GetDengjenVersion',
                request_serializer=dengjen__grpc__pb2.Empty.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.Version.FromString,
                )
        self.LoadVoice = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/LoadVoice',
                request_serializer=dengjen__grpc__pb2.VoiceConfigLocation.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.VoiceDescriptor.FromString,
                )
        self.GetVoiceInfo = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/GetVoiceInfo',
                request_serializer=dengjen__grpc__pb2.VoiceRef.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.VoiceDescriptor.FromString,
                )
        self.GetSynthesisOptions = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/GetSynthesisOptions',
                request_serializer=dengjen__grpc__pb2.VoiceRef.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.SynthesisSettings.FromString,
                )
        self.SetSynthesisOptions = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/SetSynthesisOptions',
                request_serializer=dengjen__grpc__pb2.VoiceSynthesisSettings.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.SynthesisSettings.FromString,
                )
        self.SynthesizeUtterance = channel.unary_stream(
                '/dengjen_grpc.DengjenGrpc/SynthesizeUtterance',
                request_serializer=dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.SynthesisChunk.FromString,
                )
        self.SynthesizeUtteranceRealtime = channel.unary_stream(
                '/dengjen_grpc.DengjenGrpc/SynthesizeUtteranceRealtime',
                request_serializer=dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.RealtimeAudioChunk.FromString,
                )


class DengjenGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDengjenVersion(self, request, context):
        """Return dengjen version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadVoice(self, request, context):
        """Load a voice given its config file path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoiceInfo(self, request, context):
        """Fetch details for a loaded voice
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSynthesisOptions(self, request, context):
        """Fetch a voice's current synthesis settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSynthesisOptions(self, request, context):
        """Update a voice's synthesis settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeUtterance(self, request, context):
        """Synthesize speech for a text request, streamed in chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeUtteranceRealtime(self, request, context):
        """Synthesize speech for a text request, streamed as raw audio in realtime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DengjenGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDengjenVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDengjenVersion,
                    request_deserializer=dengjen__grpc__pb2.Empty.FromString,
                    response_serializer=dengjen__grpc__pb2.Version.SerializeToString,
            ),
            'LoadVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadVoice,
                    request_deserializer=dengjen__grpc__pb2.VoiceConfigLocation.FromString,
                    response_serializer=dengjen__grpc__pb2.VoiceDescriptor.SerializeToString,
            ),
            'GetVoiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVoiceInfo,
                    request_deserializer=dengjen__grpc__pb2.VoiceRef.FromString,
                    response_serializer=dengjen__grpc__pb2.VoiceDescriptor.SerializeToString,
            ),
            'GetSynthesisOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSynthesisOptions,
                    request_deserializer=dengjen__grpc__pb2.VoiceRef.FromString,
                    response_serializer=dengjen__grpc__pb2.SynthesisSettings.SerializeToString,
            ),
            'SetSynthesisOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSynthesisOptions,
                    request_deserializer=dengjen__grpc__pb2.VoiceSynthesisSettings.FromString,
                    response_serializer=dengjen__grpc__pb2.SynthesisSettings.SerializeToString,
            ),
            'SynthesizeUtterance': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeUtterance,
                    request_deserializer=dengjen__grpc__pb2.SynthesisRequest.FromString,
                    response_serializer=dengjen__grpc__pb2.SynthesisChunk.SerializeToString,
            ),
            'SynthesizeUtteranceRealtime': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeUtteranceRealtime,
                    request_deserializer=dengjen__grpc__pb2.SynthesisRequest.FromString,
                    response_serializer=dengjen__grpc__pb2.RealtimeAudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dengjen_grpc.DengjenGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DengjenGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDengjenVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dengjen_grpc.DengjenGrpc/GetDengjenVersion',
            dengjen__grpc__pb2.Empty.SerializeToString,
            dengjen__grpc__pb2.Version.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dengjen_grpc.DengjenGrpc/LoadVoice',
            dengjen__grpc__pb2.VoiceConfigLocation.SerializeToString,
            dengjen__grpc__pb2.VoiceDescriptor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVoiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dengjen_grpc.DengjenGrpc/GetVoiceInfo',
            dengjen__grpc__pb2.VoiceRef.SerializeToString,
            dengjen__grpc__pb2.VoiceDescriptor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSynthesisOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dengjen_grpc.DengjenGrpc/GetSynthesisOptions',
            dengjen__grpc__pb2.VoiceRef.SerializeToString,
            dengjen__grpc__pb2.SynthesisSettings.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSynthesisOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dengjen_grpc.DengjenGrpc/SetSynthesisOptions',
            dengjen__grpc__pb2.VoiceSynthesisSettings.SerializeToString,
            dengjen__grpc__pb2.SynthesisSettings.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SynthesizeUtterance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dengjen_grpc.DengjenGrpc/SynthesizeUtterance',
            dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
            dengjen__grpc__pb2.SynthesisChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SynthesizeUtteranceRealtime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dengjen_grpc.DengjenGrpc/SynthesizeUtteranceRealtime',
            dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
            dengjen__grpc__pb2.RealtimeAudioChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
