name: Project sync

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened]

permissions: {}

jobs:
  sync:
    uses: ZirekHQ/.github/.github/workflows/project-sync.yml@54452127e2c87f8ecfe358fc88e0f1fe411859b3 # main
    secrets:
      PROJECT_SYNC_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
